export const universidades = [{ "titulo": "Asistente de fisioterapia", "universidad": "University of Huddersfield" },
{ "titulo": "Editor", "universidad": "Yamanashi Gakuin University" },
{ "titulo": "Ejecutivo Secretary", "universidad": "University of Northern Virginia, Campus de Praga" },
{ "titulo": "Tax Accountant", "universidad": "Universidad la Concordia" },
{ "titulo": "Tax Accountant", " universidad": "University of Texas" },
{ "titulo": "Database Administrator I", "universidad": "University of Joensuu" },
{ "titulo": "Junior Executive", "universidad": "Centre Universitaire d'Oum El Bouaghi" },
{ "titulo": "Software Engineer IV", "universidad": "Gifu Pharmaceutical University" },
{ "titulo": "Staff Accountant II", "universidad": "University of Kansas" },
{ "titulo": "Statistician I", "universidad": "Universidad de Puerto Rico, Mayaguez" },
{ "titulo": "Marketing Manager", "universidad": "Vilnius Academy of Arts" },
{ "titulo": "Operator", "universidad": "University of Development Alternative" },
{ "titulo": "Environmental Tech", "universidad": "Egerton University" },
{ "titulo": "Legal Assistant", "universidad": "Graduate University for Advanced Studies" },
{ "titulo": "Internal Auditor", "universidad": "Singhania University Rajasthan" },
{ "titulo": "VP Marketing", "universidad": "Americanos College " },
{ "titulo": "Geólogo II", "universidad": "University of Nigeria" },
{ "titulo": "Quality Engineer", "universidad": "Centre Universitaire de Jijel" },
{ "titulo": "Junior Executive", "universidad": "Universitas Merdeka Madiun" },
{ "titulo": "Database Administrator I", "universidad": "Universidad Popular de Nicaragua (UPONIC)" },
{ "titulo": "Representante de ventas", "universidad": "Huazhong Agricultural University" },
{ "titulo": "Structural Engineer", "universidad": "Royal Free Hospital School of Medicine, University of London" },
{ "titulo": "Graphic Designer", "universidad": "Ecole Supérieure de Commerce et des Affaires" },
{ "titulo": "Technical Writer", "universidad": "Oral Roberts University" },
{ "titulo": "Geologist III", " universidad": "Fachhochschule für die Wirtschaft" },
{ "titulo": "Ejecutivo de cuentas", "universidad": "Universidad Tecnológica (Loikaw)" },
{ "titulo": "Asesor Financiero", "universidad": "Gollis University" },
{ "titulo": "Technical Writer", "universidad": "Uludag University" },
{ "titulo": "Editor", "universidad": "Universidad Nicaragüense de Ciencia y Tecnológica" },
{ "titulo": "Software Consultant", "universidad": "Pakistan Institute of Engineering and Applied Sciences (PIEAS)" },
{ "titulo": "Food Chemist", "universidad": "National American University, Sioux Falls" },
{ "titulo": "GIS Technical Architect", "universidad": "Henan Normal University" },
{ "titulo": "Sales Associate", "universidad": "Liszt Ferenc Academy of Music Budapest" },
{ "titulo": "Product Engineer", "universidad": "Lithunian Institute of Physical Education" },
{ "titulo": "VP Sales", "universidad": "National University of Samoa" },
{ "titulo": "Staff Scientist", "universidad": "Université du Québec à Montréal" },
{ "titulo": "Recruiting Manager", "universidad": "Edith Cowan University" },
{ "titulo": "VP Quality Control", "universidad": "Humboldt State University" },
{ "titulo": "Compensation Analyst", "universidad": "Southwestern College Kansas" },
{ "titulo": "Especialista en Automatización I", "universidad": "Shiraz University of Medical Sciences" },
{ "titulo": "Speech Pathologist", "universidad": "American University of Central Asia" },
{ "titulo": "Web Developer III", "universidad": "Siam University" },
{ "titulo": "Compensation Analyst", "universidad": "Fachhochschule Köln" },
{ "titulo": "Nurse", "universidad": "Calvin College" },
{ "titulo": "Senior Cost Accountant ", "universidad": "Universidad Autónoma del Estado de Morelos" },
{ "titulo": "Enfermero Titulado", "universidad": "Universidad Nacional Autónoma de México" },
{ "titulo": "Ingeniero en Energía Nuclear", "universidad": "Ross University, School of Medicine" },
{ "titulo": "Tax Accountant", "universidad": "Southern University - Shreveport" },
{ "titulo": "Asistente de fisioterapia", "universidad": "Amravati University" },
{ "titulo": "Librarian", "universidad": "Iowa Wesleyan College" },
{ "titulo": "Senior Sales Associate", "universidad": "ICI University" },
{ " titulo": "Professor", "universidad": "London Institute of Management and Technology" },
{ "titulo": "Recruiting Manager", "universidad": "Northern Institute of Technology Management (NIT)" },
{ "titulo": "Social Worker", "universidad": "Université du Québec en Outaouais" },
{ "titulo": "Representante de cuenta II", "universidad": "Sekolah Tinggi Akuntansi Negara (STAN)" },
{ "titulo ": "Ingeniero químico", "universidad": "Instituto Thapar de ingeniería y tecnología" },
{ "titulo": "Diseñador web II", "universidad": "Universidad de mujeres de Kochi" },
{ "titulo": "Registrado Nurse", "universidad": "Amirkabir University of Technology" },
{ "titulo": "Senior Developer", "universidad": "Continental Theological Seminary" },
{ "titulo": "Software Engineer IV", "universidad": "Schiller International University, Heidelberg" },
{ "titulo": "Statistician II", "universidad": "Shenzhen University" },
{ "titulo": "Senior Financial Analyst", "universidad": "Universidad Francisco de Aguirre" },
{ "titulo": "Administrative Officer", "universidad": "Chongqing Technology and Business University" },
{ "titulo": "Senior Financial Analyst", "universidad": "Mills College" },
{ "titulo": "Enfermera", "universidad": "Instituto Tecnológico de Costa Rica" },
{ "titulo": "Analista de Sistemas Computacionales III", "universidad": "Escuela de Ciencias Económicas" },
{ "titulo": "VP Accounting", "universidad": "University of Social Welfare and Rehabilitation Scinences" },
{ "titulo": "Clinical Specialist", "universidad": "Birkbeck College, University of London" },
{ "titulo": "Ingeniero en Energía Nuclear", "universidad": "Aichi Institute of Technology" },
{ "titulo": "Asistente de Investigación IV", "universidad": "Universidad Carlos III de Madrid" },
{ "titulo": "Senior Sales Associate", "universidad": "Bradley University" },
{ "titulo": "Developer II", "universidad": "Obninsk State Technical University for Nuclear Power Engineering" },
{ "titulo": "Asistente de Contabilidad II", "universidad": "Marlboro College" },
{ "titulo": "Research Associate", "universidad": "Universidad Tecnológica (Meikhtila)" },
{ "titulo": "Geólogo II", " universidad": "Ecole Nationale Supérieure d'Agronomie de Montpellier" },
{ "titulo": "Junior Executive", "universidad": "Universidade Federal de Rondônia" },
{ "titulo": "Junior Executive", "universidad": "Kanazawa College of Art" },
{ "titulo": "Assistant Media Planner", "universidad": "New England School of Law" },
{ "titulo": "Health Coach II", "universidad": "Anna Maria College" },
{ "titulo": "Senior Sales Associate", "universidad": "Wuhan Automobile Polytechnical University" },
{ "titulo": "Media Manager II", "universidad": "Jones International University" },
{ "titulo": "Associate Professor", "universidad": "Universidad del Azuay" },
{ "titulo": "Media Manager III", "universidad": "University of Ancona" },
{ "titulo": " Systems Administrator IV", "universidad": "University of Jos" },
{ "titulo": "Junior Executive", "universidad": "Eastern College" },
{ "titulo": "Analog Circuit Design manager", "universidad": "University of Hartford" },
{ "titulo": "Nuclear Power Engineer", "universidad": "University of Batangas" },
{ "titulo": "Research Associate", "universidad": "Miyagi University of Education" },
{ "titulo": "Structural Analysis Engineer", "universidad": "Universidad Isaac Newton" },
{ "titulo": "Electrical Engineer", "universidad": "University of NorthWest" },
{ "titulo ": "Técnico de soporte de escritorio", "universidad": "University of Agriculture Abeokuta" },
{ "titulo": "Developer III", "universidad": "Universidad de Ciencias de la Salud de América Central (Facultad de Medicina de Belice)" },
{ "titulo": "Desktop Support Technician", "universidad": "Kurdistan University of Medical Sciences" },
{ "titulo": "Financial Analyst", "universidad": "Universidad Andina Simón Bolivar" },
{ "titulo": "Representante de Cuenta II", "universidad": "London School of Jewish Studies" },
{ "titulo": "Coordinador de Ajuste de Pagos", "universidad": "Lewis and Clark College" },
{ "titulo": "Social Worker", "universidad": "Music Academy in Lodz" },
{ "titulo": "Quality Engineer", "universidad": "Universidad Tecnológica Estatal de Bielorrusia" },
{ "titulo": "Programador I", "universidad": "Faculté Polytechnique de Mons" },
{ "titulo": "Coordinador de ajuste de pagos", "universidad": "Otis College of Art & Diseño" }]
